# Partial backend config. The bucket, region, and lock table are
# filled in at `terraform init` time from terraform/backend.hcl, which
# is generated by ./bootstrap.sh (and re-generated in CI from repo
# secrets). This way each team's sandbox has its own state without any
# hardcoded values in the repo.

terraform {
  backend "s3" {
    key     = "teamgram/terraform.tfstate"
    encrypt = true
  }
}
