name: terraform-plan

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/plan.yml"

permissions:
  id-token: write       # required for OIDC -> AWS
  contents: read
  pull-requests: write  # to comment the plan diff

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - run: terraform init -input=false

      - run: terraform fmt -check

      - run: terraform validate

      - name: Plan
        id: plan
        run: terraform plan -input=false -no-color
        continue-on-error: false
